### ISSUE TITLE
@vicimpa/rubles and nodejs 20

### ISSUE THREAD

**Issue by wisekaa03** [vicimpa/vicimpa-library#1]
```
.../dist/src/form/invoice/xls.js:11
const rubles_1 = require("@vicimpa/rubles");
                 ^

Error [ERR_REQUIRE_ESM]: require() of ES Module .../node_modules/@vicimpa/rubles/dist/index.js from .../dist/src/form/invoice/xls.js not supported.
index.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead either rename index.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in .../node_modules/@vicimpa/rubles/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

    at Object.<anonymous> (.../dist/src/form/invoice/xls.js:11:18)
    at Object.<anonymous> (.../dist/src/form/form.service.js:17:15) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v20.18.0
```

tsconfig.json:
```
  "compilerOptions": {
    "target": "ES2023",
    "module": "CommonJS",
    "moduleResolution": "Node",
```

**Comment by tolmachev21** [comment]
The same problem

**Comment by vicimpa** [comment]
Thanks. I fix this

**Comment by vicimpa** [comment]
Complete. Update library version and check this problem. 
```bash
npx npm-check-updates -u
```

**Comment by wisekaa03** [comment]
Thank you, all is fixed.
